sudo: required
services:
  - docker

before_install:
  - docker build --tag dockerland4040/docker-react -f Dockerfile .

script:
  - docker run -e CI=true dockerland4040/docker-react npm run test -- --coverage